[nets]
word_embed_size = 300
hidden_size = 600
n_layers = 1
use_mlp = true
dropout = 0.0

[train]
n_epochs = 5
batch_size = 100
min_freq = 3
ns_power = 0.75
learning_rate = 1e-3

[mscc]
question_file = 'YOUR_DATASET_DIR/Holmes.machine_format.questions.txt'
answer_file = 'YOUR_DATASET_DIR/Holmes.machine_format.answers.txt'
